//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class ItemPositionFOVRequest : Message
    {
        public const string k_RosMessageName = "Scripts/ItemPositionFOV";
        public override string RosMessageName => k_RosMessageName;

        public Std.Float32MultiArrayMsg center;

        public ItemPositionFOVRequest()
        {
            this.center = new Std.Float32MultiArrayMsg();
        }

        public ItemPositionFOVRequest(Std.Float32MultiArrayMsg center)
        {
            this.center = center;
        }

        public static ItemPositionFOVRequest Deserialize(MessageDeserializer deserializer) => new ItemPositionFOVRequest(deserializer);

        private ItemPositionFOVRequest(MessageDeserializer deserializer)
        {
            this.center = Std.Float32MultiArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.center);
        }

        public override string ToString()
        {
            return "ItemPositionFOVRequest: " +
            "\ncenter: " + center.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
