//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class UpdateChestResponse : Message
    {
        public const string k_RosMessageName = "Scripts/UpdateChest";
        public override string RosMessageName => k_RosMessageName;

        public short response;

        public UpdateChestResponse()
        {
            this.response = 0;
        }

        public UpdateChestResponse(short response)
        {
            this.response = response;
        }

        public static UpdateChestResponse Deserialize(MessageDeserializer deserializer) => new UpdateChestResponse(deserializer);

        private UpdateChestResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.response);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "UpdateChestResponse: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
