//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class UpdateChestRequest : Message
    {
        public const string k_RosMessageName = "Scripts/UpdateChest";
        public override string RosMessageName => k_RosMessageName;

        public bool update;

        public UpdateChestRequest()
        {
            this.update = false;
        }

        public UpdateChestRequest(bool update)
        {
            this.update = update;
        }

        public static UpdateChestRequest Deserialize(MessageDeserializer deserializer) => new UpdateChestRequest(deserializer);

        private UpdateChestRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.update);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.update);
        }

        public override string ToString()
        {
            return "UpdateChestRequest: " +
            "\nupdate: " + update.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
