//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class TargetInfoMsg : Message
    {
        public const string k_RosMessageName = "Scripts/TargetInfo";
        public override string RosMessageName => k_RosMessageName;

        public short id;
        public string name;
        public string expiration;

        public TargetInfoMsg()
        {
            this.id = 0;
            this.name = "";
            this.expiration = "";
        }

        public TargetInfoMsg(short id, string name, string expiration)
        {
            this.id = id;
            this.name = name;
            this.expiration = expiration;
        }

        public static TargetInfoMsg Deserialize(MessageDeserializer deserializer) => new TargetInfoMsg(deserializer);

        private TargetInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.name);
            deserializer.Read(out this.expiration);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.name);
            serializer.Write(this.expiration);
        }

        public override string ToString()
        {
            return "TargetInfoMsg: " +
            "\nid: " + id.ToString() +
            "\nname: " + name.ToString() +
            "\nexpiration: " + expiration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
